// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt92rcFJyd6tTFjrmL2kJrJidAx-DGcJ4',
    appId: '1:469693571333:web:f28ee2bcc4c7f43f46176c',
    messagingSenderId: '469693571333',
    projectId: 'alarmacomunitaria-utn-5e6be',
    authDomain: 'alarmacomunitaria-utn-5e6be.firebaseapp.com',
    storageBucket: 'alarmacomunitaria-utn-5e6be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVmDbjz-z-tFZPJ4o14t2mf43oTqHbjpY',
    appId: '1:469693571333:android:a928e8dc4f50a90846176c',
    messagingSenderId: '469693571333',
    projectId: 'alarmacomunitaria-utn-5e6be',
    storageBucket: 'alarmacomunitaria-utn-5e6be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1d7vAHnwwRR2nzSZgL4j4PgsP5rHh-k8',
    appId: '1:469693571333:ios:e95d43dfb6b7d3c446176c',
    messagingSenderId: '469693571333',
    projectId: 'alarmacomunitaria-utn-5e6be',
    storageBucket: 'alarmacomunitaria-utn-5e6be.firebasestorage.app',
    iosBundleId: 'com.community.alarm.appMobileSistemaAlarma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1d7vAHnwwRR2nzSZgL4j4PgsP5rHh-k8',
    appId: '1:469693571333:ios:e95d43dfb6b7d3c446176c',
    messagingSenderId: '469693571333',
    projectId: 'alarmacomunitaria-utn-5e6be',
    storageBucket: 'alarmacomunitaria-utn-5e6be.firebasestorage.app',
    iosBundleId: 'com.community.alarm.appMobileSistemaAlarma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt92rcFJyd6tTFjrmL2kJrJidAx-DGcJ4',
    appId: '1:469693571333:web:a7574b716e710e6f46176c',
    messagingSenderId: '469693571333',
    projectId: 'alarmacomunitaria-utn-5e6be',
    authDomain: 'alarmacomunitaria-utn-5e6be.firebaseapp.com',
    storageBucket: 'alarmacomunitaria-utn-5e6be.firebasestorage.app',
  );

}